### ISSUE TITLE
PA Review: User Auth

### ISSUE THREAD

**Issue by robinbshrestha** [robinbshrestha/MeetBrite#6]
Users can sign up, sign in, log out
Users can test the site using a demo login (currently working on the demo login)
Users can't use certain features without logging in

https://eventbrite2019.herokuapp.com/

**Comment by pvulakh** [comment]
Good work on this! A few changes to make: 
- [ ] Add footer including your contact info, link to create group, and login/signup or logout depending on whether there is a current user
- [ ] Fix css on forms - everything is stretched out vertically. Add a border radius as well
- [ ] Instead of hardcoding fake login gmail/facebook buttons, have this be a demo user button. Remember to seed your demo user :)
- [ ] Make sure logged in users can't see login/signup links in navbar; when there is a current user, the navbar should have a button to logout. 
- [ ] Style error handling (look at how meetup does it - orange text below the input field that the error came from on signup, red on login)
